/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import controlador.ControladorStock;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Deposito;

/**
 *
 * @author FIume
 */
public class GestionarStock extends javax.swing.JDialog {

    public static final String AGREGAR_STOCK="Agregar stock";
    public static final String QUITAR_STOCK="Quitar stock";
    public static final String BUSCAR_STOCK="Buscar stock";
    
            
    public GestionarStock(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
         this.setLocationRelativeTo(null);
         
       
    }
     public void ejecutar(){
        this.setVisible(true);
    }
     
    
    public void setControlador(ControladorStock control){
       
        btnAgregarStock.setActionCommand(AGREGAR_STOCK);
        btnAgregarStock.addActionListener(control);
        
        btnQuitarStock.setActionCommand(QUITAR_STOCK);
        btnQuitarStock.addActionListener(control);
       
        btnBuscar.setActionCommand(BUSCAR_STOCK);
        btnBuscar.addActionListener(control);
        
    }
    
    public void cargarLista(ArrayList<String[]> lista){
        
        DefaultTableModel tabla = new DefaultTableModel();
       
        tabla.addColumn("idProducto");
        tabla.addColumn("Descripcion");
        tabla.addColumn("Talle");
        //tabla.addColumn("idDeposito");
        tabla.addColumn("Cantidad");
        tabla.addColumn("Precio Unitario");
        tabla.addColumn("Precio De Compra");
        
        
       
        
                
       for(String[] fila : lista ){
            tabla.addRow(fila);
        }        
        TablaStock.setModel(tabla);
    }

    
    public String seleccionarFila() {
       
        int fila = TablaStock.getSelectedRow();
       
        if(fila>=0) return String.valueOf(TablaStock.getValueAt(fila,0));
           
         else {
            JOptionPane.showMessageDialog(null, "No Selecciono Ninguna Fila");
            return "null";
        }//sacamos el enable allowed y selecciona toda la fila
}

    public int CantidadStock(){
        int fila = TablaStock.getSelectedRow();
        
        return Integer.parseInt(String.valueOf(TablaStock.getValueAt(fila,3)));
    }
    
    public void LimpiarCaja(){
        txtStock.setText("0");
    }
    
    public int getStock(){
        return Integer.parseInt(txtStock.getText());
    }
    
    public String getBusqueda(){
        return txtBuscar.getText();
    }
    
     public double getTotalStock(){
        return Double.parseDouble(txtTotalStock.getText());
    }
    
    public void setTotalStock(double total){
        
        txtTotalStock.setText(""+total);
        
    }
    
    /*
    
    public void agregarDepositos(ArrayList<Deposito> depositos){
        for(Deposito d : depositos){
            cbxDepositos.addItem(d.direccion);
        }
        
    }
    */
    /*public String getTipo(){
        return cbxTipo.getSelectedItem().toString();
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaStock = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAgregarStock = new javax.swing.JButton();
        btnQuitarStock = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtTotalStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion de Stock");

        TablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "IdProducto", "Detalle", "Cantidad", "Ubicacion", "Precio Unitario", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaStock);
        TablaStock.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TablaStock.getColumnModel().getColumnCount() > 0) {
            TablaStock.getColumnModel().getColumn(5).setMinWidth(25);
            TablaStock.getColumnModel().getColumn(5).setPreferredWidth(25);
            TablaStock.getColumnModel().getColumn(5).setMaxWidth(25);
        }

        jLabel1.setText("Stock");

        btnAgregarStock.setText("Agregar Stock");

        btnQuitarStock.setText("Quitar Stock");

        txtStock.setText("0");

        jButton3.setText("Finalizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscar");

        btnBuscar.setText("Buscar");

        txtTotalStock.setEditable(false);

        jLabel2.setText("Valor del Stock $");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTotalStock, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(434, 434, 434)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 11, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarStock)
                                .addGap(27, 27, 27)
                                .addComponent(btnQuitarStock)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAgregarStock)
                    .addComponent(btnQuitarStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton3)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaStock;
    private javax.swing.JButton btnAgregarStock;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnQuitarStock;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotalStock;
    // End of variables declaration//GEN-END:variables
}
