/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import controlador.ControladorVentas;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author FIume
 */
public class RealizarVenta extends javax.swing.JDialog{

   public static final String VER_DETALLEV="VER DETALLE DEL PRODUCTO";
   public static final String AGREGAR_PROD="AGREGAR PRODUCTO A LA VENTA";
   public static final String QUITAR_PROD="QUITAR PRODUCTO DE LA VENTA";
   public static final String FINALIZAR_VENTA="FINALIZAR LA VENTA";
   public static final String CANCELAR_VENTA="CANCELAR LA VENTA";
   public static final String DESCUENTO_VENTA="HACER DESCUENTO";
   private int filaSeleccionada;
           
    public RealizarVenta(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        
         SpinnerNumberModel spn = new SpinnerNumberModel();
         spn.setMaximum(100);
         spn.setMinimum(1);
         spn.setValue(1);
         spnCantidadAgregar.setModel(spn);
        
         
         SpinnerNumberModel spn2 = new SpinnerNumberModel();
         spn.setMaximum(100);
         spn.setMinimum(1);
         spn2.setValue(1);
         //spnCantidadQuitar.setModel(spn2);
    }
    
    public void ejecutar(){
        this.setVisible(true);
    }
    
    public void setControlador(ControladorVentas control){
       btnVerDetalle.setActionCommand(VER_DETALLEV);
       btnVerDetalle.addActionListener(control);
       
       btnAgregar.setActionCommand(AGREGAR_PROD);
       btnAgregar.addActionListener(control);
       
       btnQuitar.setActionCommand(QUITAR_PROD);
       btnQuitar.addActionListener(control);
       
       btnFinalizarVenta.setActionCommand(FINALIZAR_VENTA);
       btnFinalizarVenta.addActionListener(control);
       
       btnCancelar.setActionCommand(CANCELAR_VENTA);
       btnCancelar.addActionListener(control);
       
       btnDescuento.setActionCommand(DESCUENTO_VENTA);
       btnDescuento.addActionListener(control);
    }
        
    
    
    public void cargarLista(ArrayList<String[]> lista){
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("idProducto");
        tabla.addColumn("Producto");
        tabla.addColumn("Cantidad");
        tabla.addColumn("Subtotal");
      
        
        
       for(String[] fila : lista ){
            tabla.addRow(fila);
        }        
        tablaRVenta.setModel(tabla);
    }
    
    
     
     public void RellenarComboProductos(ArrayList<Producto> producto){
        for(Producto p : producto){
            cbxProducto.addItem(p.getCodigo()+" - "+p.getDescripcion()+" T " + p.getTamanio());
            
        }
    }
     
    public int getCantidadAgregar(){
        return Integer.parseInt(spnCantidadAgregar.getValue().toString());
    }   
      
     
    
    public String getPD(){
        return cbxProducto.getSelectedItem().toString().substring(0,2);// Tomamos de la cadena Desde el indice 0 al 2
    }
    
    
     public void setSubTotal(double SubTotal){
        txtSubtotal.setText(Double.toString(SubTotal));
    }
     
     public double getTotal(){
         return Double.parseDouble(txtSubtotal.getText());
     }
     
     public Object getTarjeta(){
         return CheckTarjeta.getSelectedObjects();
         
     }
     
     public void setFilaSeleccionada(int filaSeleccionada){
         this.filaSeleccionada=filaSeleccionada;
     }
     
     public int getFilaSeleccionada(){
         return filaSeleccionada;
     }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRVenta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnVerDetalle = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        txtSubtotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnFinalizarVenta = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CheckTarjeta = new javax.swing.JCheckBox();
        spnCantidadAgregar = new javax.swing.JSpinner();
        cbxProducto = new javax.swing.JComboBox<String>();
        btnDescuento = new javax.swing.JButton();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal - Registrar Ventas");

        tablaRVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idProducto", "Descripcion", "Precio"
            }
        ));
        tablaRVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaRVentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaRVenta);
        tablaRVenta.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel2.setText("Id Producto/Descripcion/Talle");

        btnVerDetalle.setText("Ver Detalles");

        btnAgregar.setText("Agregar ");

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        txtSubtotal.setEditable(false);
        txtSubtotal.setText(" ");

        jLabel3.setText("Subtotal  $");

        btnFinalizarVenta.setText("Finalizar Venta");

        btnCancelar.setText("Cancelar");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CheckTarjeta.setText("Pago Tarjeta");

        btnDescuento.setText("Realizar Descuento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVerDetalle)
                                .addGap(196, 196, 196)))
                        .addComponent(spnCantidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(btnCancelar)
                        .addGap(184, 184, 184)
                        .addComponent(btnFinalizarVenta)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(75, 75, 75)
                        .addComponent(btnQuitar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDescuento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CheckTarjeta)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerDetalle))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQuitar)
                        .addComponent(btnAgregar)
                        .addComponent(spnCantidadAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(CheckTarjeta)
                            .addComponent(btnDescuento))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFinalizarVenta)
                            .addComponent(btnCancelar)
                            .addComponent(jButton1)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaRVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaRVentaMouseClicked
        int filaVenta = tablaRVenta.rowAtPoint(evt.getPoint());
        filaSeleccionada = Integer.parseInt(String.valueOf(tablaRVenta.getValueAt(filaVenta, 0)));
        this.setFilaSeleccionada(filaSeleccionada);
    }//GEN-LAST:event_tablaRVentaMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckTarjeta;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnFinalizarVenta;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnVerDetalle;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnCantidadAgregar;
    private javax.swing.JTable tablaRVenta;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables
}
